### ISSUE TITLE
Not Deployable

### ISSUE THREAD

**Issue by JunioraTm** [salesforce-experiencecloud/MultiLevelNavigationMenu#2]
I am not sure if anyone has tried to use or deploy this from GitHub, but both this and the version under the SalesforceLabs repo referenced on the Quip Info (https://quip.com/4EMxAD8a2uEn) are not deployable as-is.

In order for me to use this repo, I had to create a Dev Org, install the solution from App Exchange and then start bringing in missing things as well as modify the code so that references were correct.

This includes (but not limited to)
- Pulling in the Global Value Set for Languages (I named it Language Codes since my client's org already had a Languages global picklist) ... Without having this, the objects won't deploy.
- Objects in the Repo are generically named, but the Apex and LWCs appears to be pulled directly from the Managed Package and use "ccnavmenus__" in their references.
- There are other changes / supplements I had to include, modify in order to get this repo deployable, which I don't recall

My concern with the above is that there are things in the Managed Package that aren't in this repo. Why that is important to me is as follows:
- Using Experience Cloud LWR I am seeing the navigation fully reload (at least from the code in this repo). I believe that unlike Aura, this is because relative links in LWR aren't sufficient and it needs to be NavigationMixins. I am curious if the App Exchange version works differently than what I am seeing, which means it is being kept up to date but the repo isn't (TBD).
- The solution is good, but I have actually had to make some big customizations to allow for more responsive design (mobile detection was ok, not great), included an option for a mega menu (two tiers always show), adding the ability to include images in groups, include ability to provide a disclaimer modal for email and 3rd party sites before opening a link. I am happy to show / walk through some of my modifications if of interest.

**Comment by gtabboud** [comment]
Hi @JunioraTm ,

The code in this repo is exactly the same code as what's in the managed package - which is why it's a bit of a process to remove the "namespaces" for every commit to make it easier to deploy...it's a compromise vs keeping this in sync with the latest version of the app.

As far as navigation in LWR, that's a known issue that the product team is currently reviewing. In Aura, relative links anywhere on the page were treated as in-app navigation - that does not seem to be the case in LWR. I believe it's a gap and it will be brought up to par with Aura, otherwise the use of navigation mixin in custom LWCs will always be a partial solution, since none of the relative links in components like rich text editor and html editor and others will work without reloading the page.

Lastly, if you are open to it, I've love to see a demo of the modifications you've done and if it's feasible to incorporate into the app and this repo, and you're open to it, we can discuss as well. Let me know and we can figure out next steps.

**Comment by JunioraTm** [comment]
Hey @gtabboud, 

Completely get that from a namespace standpoint. However, there are things missing that would be good to include such as:
- Global Value Set for Languages
- Permission Set for Site Viewer and Site Editor for access to the custom objects, fields and associated apex classes (not currently in the managed package)
- Sharing Rules which are key to have for anonymous Experience Cloud sites (more of an example as it would need to be modified on a per guest user basis)

Definitely game to schedule some time to walk through some of the above suggestions as well as what we have done with the solution. I have tried to keep as much of the core the same as possible, but there are some little tweaks I have made as well as major that might be of interest. Feel free to give me a shout at justinf@slalom.com and we can schedule some time to talk.

**Comment by gtabboud** [comment]
I agree on the Global Value set, that's a miss and will look into including it in the repo. 

The Permission set I could go either way on, because an admin could choose the profile route to grant access as well, but I guess it wouldn't hurt to have one - something that I'd have to create/test and then add to the repo as there isn't one there currently.

Sharing rules wouldn't be something that I'd include in this package or repo. The need for those are documented here: https://salesforce.quip.com/4EMxAD8a2uEn and those would need to be configured in subscriber orgs on a case-by-case basis, which may differ from case to case.

I'll reach out to schedule a sync with you - thanks for the offer!

**Comment by JunioraTm** [comment]
Don't have access to that Quip document. Seems like it requires an @salesforce.com email, but I get the gist of what you are saying.

Look forward to connecting with you more on this and walking through 1 site we already have live with 3 styling variations of the navigation in place as well as what we are currently working on which has more of a mega-menu feel to it.

**Comment by gtabboud** [comment]
Try opening it up incognito/private browsing - sometimes if you're logged into to another account it might detect that and give you an access error, but the doc should be publicly accessible.

**Comment by JunioraTm** [comment]
Ah, yeah, good call, that did the trick. And now that I see it, I definitely heavily used this documentation when I was first getting started. Thanks!

**Comment by gtabboud** [comment]
Hey @JunioraTm - Just updated the package.xml to include the following metadata:

- FlexiPages
- Page Layouts
- Applications
- Global Value Sets
- Custom Tabs

Let me know if I've missed anything, otherwise I can close out this thread.

Thanks for your feedback on this!

**Comment by JunioraTm** [comment]
Look great, thanks @gtabboud!
